# .gitlab-ci.yml -- to automate Docker Nikola image builds
# Copyright (C) 2016-2018  Olaf Meeuwissen
#
# License: GPL-3.0+

variables:
  _VERSION: "7.8.11"
  TEST_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  GOOD_IMAGE: "$CI_REGISTRY_IMAGE:$_VERSION"
  LAST_IMAGE: "$CI_REGISTRY_IMAGE:latest"

image: docker:latest
services:
- docker:dind

before_script:
- docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" registry.gitlab.com

auto-update:
  only:
  - schedules
  script:
  - ./update.sh
  - git push origin master

build:
  stage: build
  except:
  - schedules
  script:
  - docker pull "$LAST_IMAGE" || true
  - docker build --build-arg _VERSION="==$_VERSION"
           --tag "$TEST_IMAGE" .
  - docker push  "$TEST_IMAGE"

check:
  stage: test
  except:
  - schedules
  script:
  - docker pull "$TEST_IMAGE"
  - docker run -v $PWD:/root:ro "$TEST_IMAGE"
           /bin/sh -e /root/test.sh

release:
  stage: deploy
  only:
  - master
  except:
  - schedules
  script:
  - docker pull "$TEST_IMAGE"
  - docker tag  "$TEST_IMAGE" "$GOOD_IMAGE"
  - docker push               "$GOOD_IMAGE"
  - docker tag                "$GOOD_IMAGE" "$LAST_IMAGE"
  - docker push                             "$LAST_IMAGE"
