# .gitlab-ci.yml -- to automate Docker Nikola image builds
# Copyright (C) 2016-2019  Olaf Meeuwissen
#
# License: GPL-3.0+

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  _VERSION: "8.0.2"
  TEST_IMAGE: "$CI_REGISTRY_IMAGE/by-sha:$CI_COMMIT_SHA"
  GOOD_IMAGE: "$CI_REGISTRY_IMAGE:$_VERSION"
  LAST_IMAGE: "$CI_REGISTRY_IMAGE:latest"

image: docker:latest
services:
- docker:dind

before_script:
- echo "$CI_REGISTRY_PASSWORD"
       | docker login --username "$CI_REGISTRY_USER"
                      --password-stdin "$CI_REGISTRY"

auto-update:
  only:
  - schedules
  script:
  - apk add --no-cache curl git jq
  - ./update.sh
  - git diff --quiet origin/$CI_COMMIT_REF_NAME

build:
  stage: build
  except:
  - schedules
  script:
  - docker pull "$LAST_IMAGE" || true
  - docker build --build-arg _VERSION="==$_VERSION"
           --tag "$TEST_IMAGE" .
  - docker push  "$TEST_IMAGE"

check:
  stage: test
  except:
  - schedules
  script:
  - docker pull "$TEST_IMAGE"
  - docker run -v $PWD:/root:ro "$TEST_IMAGE"
           /bin/sh -e /root/test.sh

release:
  stage: deploy
  only:
  - master
  except:
  - schedules
  script:
  - docker pull "$TEST_IMAGE"
  - docker tag  "$TEST_IMAGE" "$GOOD_IMAGE"
  - docker push               "$GOOD_IMAGE"
  - docker tag                "$GOOD_IMAGE" "$LAST_IMAGE"
  - docker push                             "$LAST_IMAGE"
