# .gitlab-ci.yml -- to automate Docker Nikola image builds
# Copyright (C) 2016  Olaf Meeuwissen
#
# License: GPL-3.0+

image: docker:latest
services:
- docker:dind

before_script:
- docker info
- docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com

build:
  stage: build
  script:
  - docker build -t "$CI_REGISTRY_IMAGE" .
  - docker push "$CI_REGISTRY_IMAGE"

check:
  stage: test
  script:
  - docker run "$CI_REGISTRY_IMAGE" false
  - test -n "$CI_BUILD_TAG"

release:
  stage: deploy
  script:
  - docker pull "$CI_REGISTRY_IMAGE"
  - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":"$CI_BUILD_TAG"
  - docker push "$CI_REGISTRY_IMAGE":"$CI_BUILD_TAG"
  only:
  - master
